name: "[Experimental] High-Speed Map Mode"
overview: "This overrides the steering points calculation to allow for higher speeds."
description: |
  This experimental plugin is designed to enable higher travel speeds in ETS when using ETS2LA, while reducing unstable or erratic behavior.

  Note: This plugin will only ever work on the Python version of ETS2LA, simply because C# probably will not need it nor will I touch that part of the C# rewrite
image_url: ""
version: "1.0.0"
author: "Playzzero97"
